my_pro/my_pro/urls.py
from django.contrib import admin
from django.urls import path,include
from myfinal_app import views

urlpatterns = [

path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('myfinal_app/',include('myfinal_app.urls')),
]

my_pro/myfinal_app/urls.py
from django.urls import path
from myfinal_app import views

app_name = 'myfinal_app'

urlpatterns=[
path('other/',views.other,name='other'),
]

my_pro/myfinal_app/models.py
from django.db import models

# Create your models here.

my_pro/myfinal_app/views.py
from django.shortcuts import render


def index(request):
    return render(request,'myfinal_app/index.html')

def other(request):
    return render(request,'myfinal_app/other.html')

my_pro/templates/myfinal_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

  </head>
  <body>
      <nav class='navbar navbar-default navbar-fixed-top'>
        <div class="container">
       <ul class="nav navbar-nav">
       <li><a class='navbar-brand' href="{% url 'index' %}">Brnad</a></li>
       <li><a class='navbar-brand' href="{% url 'myfinal_app:other' %}">Other</a></li>
       <li><a class='navbar-brand' href="{% url 'admin:index' %}">Admin</a></li>
     </ul>
        </div>
      </nav>

<div class="conatiner">

        {% block body_block %}



        {% endblock %}

      </div>

  </body>
</html>

my_pro/templates/myfinal_app/index.html
<!DOCTYPE html>
{% extends 'myfinal_app/base.html' %}
  {% block body_block %}



      <h1>Index</h1>
      <h1>mana</h1>
      <h1>hello</h1>
      {% endblock %}

my_pro/templates/myfinal_app/other.html
<!DOCTYPE html>
{% extends 'myfinal_app/base.html' %}
  {% block body_block %}
        <h1></h1><br>
        <h1></h1><br>
        <h1>hello</h1>
        <h1>This is manas</h1>
        {% endblock %}